baseURL = 'https://www.torontobusinessdirectory.com/'
languageCode = 'en-us'
title = 'We the North | Toronto Business Listings'
paginate = 8

[params]
    dateFormat = "October 2, 2023"
    description = "Discover Toronto Business Listings"


[taxonomies]
    category = "categories"
    author = "authors"
